Feature1
murthy2609/Hello-Microverse pull request #1
Opened 2023-02-14 14:48 UTC by murthy2609

2023-02-14 15:04 UTC, Alfredbis29 requested changes
### Hi @murthy2609  ,
 You did a great job so far 👏🏼 👏🏼 There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/ea601010ed4ac26655ecf8ef2441aea1c7d8b3ab5cc23c495c981ea928fb2043/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) 
 
 ### To highlight 💪🏻
Good Commit messages :white_check_mark:
:+1:  Good job! so far !

## STATUS: CHANGES REQUESTED 

- [ ] I can see that you did a great of adding a `README` file in your project as required in this project but it still need to be more descriptive and professional , let try to make it professional and attractive, I suggest you to have a look on this template provides by Microverse Team , please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project. :wink:  :smile: 

- [ ] I Just notice that you just forget again an important part that you will using all your journey at MIcroverse , kindly Set up `Linters` in your project since `Linters` are tools that analyze code for potential issues, such as syntax errors, unused variables, and code style violations :wink: , You can use this Documentation to Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config)

- [ ] As required for this project There is a .gitignore file listing test.md file and node_modules directory (as it can be added by accident while setting up Linters) You should ignore those two files in your `.gitignore` file. kindly take care of this for your project to match all requirement then ask for another review :face_with_spiral_eyes:  :wink: 

- [ ] I can see that you didn't add the description for this PR kindly add it since it help us to understand what you did in this milestone of your project :wink:  you can add it here :point_down:   but if you need to add description to your PR click on the 3 dot is mentioned on the image bellow then click on edit then you will be able to write down your PR description 
![Screenshot from 2023-02-14 16-59-17](https://user-images.githubusercontent.com/88894525/218775269-a375de43-24ed-4051-9d68-c6e6faa961d0.png)



_Please Check the comments under the review and make all required changes_
 
## Optional suggestions

- [ ] Kindly follow the Project Guidelines and I'm sure that you will make it , then when you are ready you can request for another review :wink:  :muscle: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 Cheers and Happy coding! :clap: :clap: :clap: :computer: Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please ping me @alfredbis29 when you comment so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 17:42 UTC, shella12 requested changes
Hi @murthy2609 , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Added descriptive PR ✅ 
- Added files to .gitignore ✅ 
- Setup linter files ✅ 

 ## Required Changes ♻️

- [ ] While you made a great effort adding linter files to your project as suggested by the previous reviewer, you still have to fix your linter errors . Please fix your `stylelint` errors. You can do this manually or you can use auto fix command in your terminal:  

```sh 

npx stylelint "**/*.{css,scss}" —fix  `

```
  
_Also check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] I suggest using a more descriptive name for your feature branch instead of `feature1`. Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section’). Its one of the requirements of the project that you should consider in the future.

  <img width="624" alt="Screenshot 2023-02-14 at 10 35 26 PM" src="https://user-images.githubusercontent.com/44798044/218815001-3a1322cd-eab6-40e8-b0d7-b7f3d96a2c52.png">


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 17:42 UTC, shella12 commented on Index.html
> +</body>
- [ ] [OPTIONAL] I suggest wrapping your `h1` element around in a `header` tag as it was also mentioned in the [project reqirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) document
> - A .html file that includes a header with the text "Hello Microverse!". Use h1 tag for that.

2023-02-14 17:42 UTC, shella12 commented on README.md
> +
- [ ] You have added README template provided by the Microverse. Great job👏 👏 . But as suggested by the previous reviewer you should make it a little bit 🤏 🤏 more descriptive to make it look more professional 😎 👍 . Documentation skills are greatly valued in tech industry. A well documented project might attract recruiters and can become a reason for your hiring. Here are the lists of a few changes you can do to your README to make it look more professional: 

     - [ ] I would suggest removing the Microverse logo from your readme. Logo is your personal 🧑‍🦱 symbol of 
     branding and ownership. While the project is suggested by the Microverse, it is owned solely by you 🛄  there 
     is no need to add Microverse logo into your projects readme as it does not reflect your project. Optionally, you 
     can replace with your own logo 📛 if you want 👍 👍 . You should also remove `Microverse README Template` 
     adding from the top of your README
    - [ ] I suggest you remove text like

         > Describe the tech stack and include only the relevant sections that apply to your project.

         >Describe between 1-3 key features of the application.

        etc.,
        from your README as they were added in the template to explain purpose of each heading. It doesn't reflect 
        your project and shouldn't be in your project's README. This skill depicts your `Attention to detail` which is 
       another attractive skill recruiters look for 😉 
     - [ ] Great job 👍  for adding a license link into your project but there is a problem with link. You didn't add 
       licence file to your project. :smile: You can add this file using these [guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) :blush:

2023-02-14 19:02 UTC, franclobo requested changes
Hi @murthy2609, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/218832417-03b3a97c-a903-4e6a-96df-16812fe8bd79.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors ✔️ 
- Correct use of `header` tag ✔️ 
- Correct Github flow ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- **[OPTIONAL]** As requested by the first code reviewer please 🙏🏽  edit the PR description, it is important to have professional documentation explaining the activities or changes in the current branch to be approved. It is a general requirement for all projects in the future otherwise the project will be invalidated ❌.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 04:19 UTC, franclobo approved these changes
Hi @murthy2609, 

# STATUS: APPROVED 😃 

![git-merge](https://user-images.githubusercontent.com/58642949/218928544-d2bd1ca7-0988-43d9-906a-6519a29f703b.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️
- Correct use of header tag ✔️
- Correct Github flow ✔️
- Descriptive PR ✔️

## Optional suggestions

- **[OPTIONAL]** Between the "Key features" and "Author" sections there are more sections that should always be present in your README file, this is a general requirement for all projects otherwise it will be invalidated ❌ in the future projects. Please 🙏🏽 add the `Live demo` and `Getting started` sections because all main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 04:19 UTC, franclobo commented on README.md
> +## 👥 Authors <a name="authors"></a>
- **[OPTIONAL]** Between the "Key features" and "Author" sections there are more sections that should always be present in your README file, this is a general requirement for all projects otherwise it will be invalidated ❌ in the future projects. Please 🙏🏽 add the `Live demo` and `Getting started` sections because all main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo.

2023-02-15 04:24 UTC, merged